name:                purview
version:             0.1.0.0
github:              "purview-framework/purview"
license:             BSD3
author:              "Ian Davidson"
maintainer:          "bontaq@gmail.com"
copyright:           "2022 Ian Davidson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/purview#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- stm
- bytestring
- raw-strings-qq
- warp
- wai
- wai-websockets
- wai-extra
- websockets
- scotty
- time
- freer-simple

build-tools:
  - hspec-discover == 2.*

library:
  source-dirs: src
  exposed-modules:
    - Purview
    - Component
    - Diffing
    - EventHandling
    - PrepareTree
    - Rendering
    - Events
  ghc-options:
    - -Wincomplete-patterns

executables:
#  purview-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - purview

  purview-perf-test:
    main: Criterion.hs
    source-dirs: performance
    ghc-options:
    - -main-is Criterion
    dependencies:
    - purview
    - criterion

tests:
  purview-test:
    main:                Spec.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Spec
    dependencies:
    - purview
    - QuickCheck
    - hspec
