# credit to https://kodimensional.dev/github-actions

name: run-tests
on: push
jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.7.3"]
        ghc: ["9.2.8"]

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v2.1.3
      name: Cache
      with:
        path: |
          ~/.stack
          ./.stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Set Env
      run: |
        echo "/usr/lib/postgresql/13/bin/" >> $GITHUB_PATH
      shell: bash

    - name: Test
      run: |
        stack test --system-ghc
